```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load("knitr","ggplot2","rstanarm","dplyr","tidyverse","PerformanceAnalytics", "grid","gridExtra","readxl","ggbiplot","devtools","caret","leaps","MASS")
install_github("vqv/ggbiplot")

```




```{r warning=FALSE}
TKA_data <- read_xlsx("TKAsheet.xlsx")

TKA_data$V3X_Contal_KL <- as.numeric(TKA_data$V3X_Contal_KL)
TKA_data_1 <- TKA_data %>% drop_na()
colnames(TKA_data_1)
# TKA_data <- TKA_data_1[, c(3, 4,5,17,10,7,9)]
# TKA_data <- TKA_data_1[, c(3,17,11,10,32,26)]
TKA_data <- TKA_data_1[, c(3,17,11,10,32,26,4,5,7,9)]
chart.Correlation(TKA_data[,2:6], histogram=TRUE, pch=20)
```

# variable selection with AIC
```{r}
variable_list <- colnames(TKA_data)
selected_list <- variable_list[1]
# fit_test <- glm(had_tkr_contra ~ ., family = 'binomial', data = TKA_data)
# test_score<- AIC(fit_test)
score <- 999
for (i in 2:length(variable_list)){
  option_list<- append(selected_list,variable_list[i])
  data_loop <- TKA_data[,option_list]
 fit_test <- glm(had_tkr_contra ~ ., family = 'binomial', data = data_loop)
 test_score<- AIC(fit_test)
 if (test_score<score)
   selected_list <- option_list
    score <- test_score
  
}
# fit_1<- glm(had_tkr_contra ~ ., family = "binomial", data = TKA_data)
# fit_1
```

# bakcward selection
```{r}
full.model <- glm(had_tkr_contra ~ ., family = 'binomial', data = TKA_data)
step.model <- stepAIC(full.model, direction = "both", 
                      trace = FALSE)
summary(step.model)
models <- regsubsets(had_tkr_contra~., data = TKA_data, nvmax = 5,
                     method = "backward")
summary(models)


set.seed(100)
# Set up repeated k-fold cross-validation
train.control <- trainControl(method = "cv", number = 10)
# Train the model
step.model <- train(as.numeric(had_tkr_contra) ~., data = TKA_data,
                    method = "leapBackward", 
                    tuneGrid = data.frame(nvmax = 1:5),
                    trControl = train.control
                    )
step.model$results
summary(step.model$finalModel)
coef(step.model$finalModel, 4)
```



# model with clint's refered vaiables
```{r}
fit_1<- glm(had_tkr_contra ~ DIF_STEPLENGTH_CM_TKRminContra + CADENCE + VELOCITY + DIF_SWING_TIME_SEC + AVG_HH_BASE_SUPP_CM, family = "binomial", data = TKA_data)
# summary(fit_1
```

```{r}
variable.names(TKA_data)
tka_pca <- prcomp(TKA_data, center = TRUE,scale. = TRUE)
ggbiplot::ggbiplot(tka_pca,ellipse=TRUE,obs.scale = .5, var.scale = 1, labels=rownames(tka_pca), groups=TKA_data$had_tkr_contra)
```


